- name: Setup PostgreSQL
  hosts: postgres
  become: true
  vars:
    pg_conf_path_redhat: "/var/lib/pgsql/data/postgresql.conf"
    pg_hba_path_redhat: "/var/lib/pgsql/data/pg_hba.conf"
  roles:
    - postgres_server

- name: Setup firewall to allow PostgreSQL connection
  hosts: all
  become: true
  roles:
    - firewall

- name: Check DB connection from client
  hosts: client
  become: true
  vars:
    db_host: "{{ db_host }}"
  roles:
    - db_client
